#!/bin/sh

HOME_DIR=/home/marino/sanitized
ORIG_DIR=gps-5.0.1-src
TARG_DIR=gps-5.0.1
NEW_BZ2=${TARG_DIR}.tar.bz2
TAR_FILE=gps-5.0.1-gpl-src.tar.gz

cd ${HOME_DIR}
rm -rf ${ORIG_DIR}
rm -rf ${TARG_DIR}
rm -rf ${NEW_BZ2}

/usr/bin/tar -xf ${TAR_FILE}
mv ${ORIG_DIR} ${TARG_DIR}

rm ${TARG_DIR}/templates_parser/tp_shared.gpr.orig
rm ${TARG_DIR}/shared.gpr.orig

mkdir ${TARG_DIR}/docx
mv ${TARG_DIR}/docs/gps.pdf ${TARG_DIR}/docx
rm -rf ${TARG_DIR}/docs
mv ${TARG_DIR}/docx ${TARG_DIR}/docs
echo "all:" > ${TARG_DIR}/docs/Makefile.in

/usr/bin/tar -cyf ${NEW_BZ2} ${TARG_DIR}
